import { Code } from "./key-codes";
import { KeyboardLayout } from "./keyboard-layout";

export const Key: Record<string, { layout?: KeyboardLayout; hotkey: Code[] }> =
  {
    "0": { hotkey: [Code.KEY_0] },
    "1": { hotkey: [Code.KEY_1] },
    "2": { hotkey: [Code.KEY_2] },
    "3": { hotkey: [Code.KEY_3] },
    "4": { hotkey: [Code.KEY_4] },
    "5": { hotkey: [Code.KEY_5] },
    "6": { hotkey: [Code.KEY_6] },
    "7": { hotkey: [Code.KEY_7] },
    "8": { hotkey: [Code.KEY_8] },
    "9": { hotkey: [Code.KEY_9] },
    A: { hotkey: [Code.KEY_A] },
    B: { hotkey: [Code.KEY_B] },
    C: { hotkey: [Code.KEY_C] },
    D: { hotkey: [Code.KEY_D] },
    F: { hotkey: [Code.KEY_F] },
    E: { hotkey: [Code.KEY_E] },
    G: { hotkey: [Code.KEY_G] },
    H: { hotkey: [Code.KEY_H] },
    I: { hotkey: [Code.KEY_I] },
    J: { hotkey: [Code.KEY_J] },
    K: { hotkey: [Code.KEY_K] },
    L: { hotkey: [Code.KEY_L] },
    M: { hotkey: [Code.KEY_M] },
    N: { hotkey: [Code.KEY_N] },
    O: { hotkey: [Code.KEY_O] },
    P: { hotkey: [Code.KEY_P] },
    Q: { hotkey: [Code.KEY_Q] },
    R: { hotkey: [Code.KEY_R] },
    S: { hotkey: [Code.KEY_S] },
    T: { hotkey: [Code.KEY_T] },
    U: { hotkey: [Code.KEY_U] },
    V: { hotkey: [Code.KEY_V] },
    W: { hotkey: [Code.KEY_W] },
    X: { hotkey: [Code.KEY_X] },
    Y: { hotkey: [Code.KEY_Y] },
    Z: { hotkey: [Code.KEY_Z] },
    "£": { hotkey: [Code.SHIFT, Code.KEY_3] },
    ";": { hotkey: [Code.OEM_1] },
    ":": { hotkey: [Code.SHIFT, Code.OEM_1] },
    "/": { hotkey: [Code.OEM_2] },
    "?": { hotkey: [Code.SHIFT, Code.OEM_2] },
    "'": { hotkey: [Code.OEM_3] },
    "@": { hotkey: [Code.SHIFT, Code.OEM_3] },
    "[": { hotkey: [Code.OEM_4] },
    "{": { hotkey: [Code.SHIFT, Code.OEM_4] },
    "\\": { hotkey: [Code.OEM_5] },
    "|": { hotkey: [Code.SHIFT, Code.OEM_5] },
    "]": { hotkey: [Code.OEM_6] },
    "}": { hotkey: [Code.SHIFT, Code.OEM_6] },
    "#": { hotkey: [Code.OEM_7] },
    "~": { hotkey: [Code.SHIFT, Code.OEM_7] },
    "`": { hotkey: [Code.OEM_8] },
    "¬": { hotkey: [Code.SHIFT, Code.OEM_8] },
    "¦": { hotkey: [Code.MENU, Code.CONTROL, Code.OEM_8] }, // MENU IS ALT
  };
